spring:
  application:
    name: petstore-analyzer

springdoc:
  show-actuator: false
  swagger-ui:
    path: /api
    tags-sorter: alpha

  api-docs:
    path: /api-docs



services:
  petstore:
    base-url: https://petstore3.swagger.io/api/v3
    connection-timeout: 20000
